/*
 * MIT License
 *
 * Copyright (c) 2025 MetaAgent
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.metaagent.framework.core.agent;

import org.metaagent.framework.core.agent.loop.AgentLoopControlStrategy;
import org.metaagent.framework.core.agent.loop.MaxLoopCountAgentLoopControl;
import org.metaagent.framework.core.tool.ToolContext;
import org.metaagent.framework.core.tool.executor.ToolExecutorContext;
import org.metaagent.framework.core.tool.manager.ToolManager;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Sinks;

import java.util.concurrent.atomic.AtomicReference;

/**
 * Abstract {@link Agent} implementation.
 *
 * @author vyckey
 */
public abstract class AbstractAgent<
        AgentInput extends org.metaagent.framework.core.agent.input.AgentInput,
        AgentOutput extends org.metaagent.framework.core.agent.output.AgentOutput>
        extends AbstractMetaAgent<AgentInput, AgentOutput> implements Agent<AgentInput, AgentOutput> {
    protected ToolManager toolManager = ToolManager.create();

    protected AbstractAgent(String name) {
        super(name);
    }

    @Override
    public ToolManager getToolManager() {
        return toolManager;
    }

    @Override
    public AgentLoopControlStrategy<AgentInput, AgentOutput> getLoopControlStrategy() {
        return new MaxLoopCountAgentLoopControl<>(1);
    }

    @Override
    protected AgentOutput doRun(AgentInput input) {
        return Agent.super.run(input);
    }

    @Override
    protected Flux<AgentOutput> doRunFlux(AgentInput input) {
        Agent<AgentInput, AgentOutput> agent = this;

        AtomicReference<AgentStateHolder<AgentInput, AgentOutput>> holderRef = new AtomicReference<>(
                new AgentStateHolder<>(input, null)
        );
        Sinks.Many<AgentOutput> fullOutputSink = Sinks.many().replay().latest();

        // perform first step
        Flux<AgentOutput> firstStepFlux = stepFlux(holderRef.get().input(), fullOutputSink);

        // perform remaining steps util loop control strategy tells us to stop
        return firstStepFlux
                .concatWith(Flux.defer(() -> fullOutputSink.asFlux()
                        .flatMap(fullOutput -> {
                            // update input and output state
                            holderRef.set(new AgentStateHolder<>(holderRef.get().input(), fullOutput));

                            if (getLoopControlStrategy().shouldContinueLoop(agent, input, fullOutput)) {
                                // perform next step
                                AgentInput nextInput = buildNextStepInput(holderRef.get().input(), holderRef.get().fullOutput());
                                holderRef.set(new AgentStateHolder<>(nextInput, null));
                                return stepFlux(nextInput, fullOutputSink);
                            } else {
                                // stop loop
                                return Flux.empty();
                            }
                        })
                        .takeWhile(output -> getLoopControlStrategy()
                                .shouldContinueLoop(agent, input, holderRef.get().fullOutput())
                        )
                ))
                .doFinally(signal -> fullOutputSink.tryEmitComplete());
    }

    protected Flux<AgentOutput> stepFlux(AgentInput input, Sinks.Many<AgentOutput> fullOutputSink) {
        AtomicReference<AgentOutput> fullOutputRef = new AtomicReference<>();
        return super.stepFlux(input)
                .doOnNext(partialOutput -> {
                    fullOutputRef.set(mergeAgentOutput(fullOutputRef.get(), partialOutput));
                })
                .doOnComplete(() -> fullOutputSink.tryEmitNext(fullOutputRef.get()));
    }

    /**
     * Merges partial output generated by streaming model with full output.
     *
     * @param fullOutput The full output
     * @param output     The partial output
     * @return The merged output
     */
    protected AgentOutput mergeAgentOutput(AgentOutput fullOutput, AgentOutput output) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    /**
     * Builds the next step input for the streaming agent.
     *
     * @param input  The current input for the agent.
     * @param output The output from the current step.
     * @return The next step input for the agent.
     */
    protected AgentInput buildNextStepInput(AgentInput input, AgentOutput output) {
        return input;
    }

    record AgentStateHolder<I, O>(I input, O fullOutput) {
    }

    protected ToolExecutorContext buildToolExecutorContext(AgentInput input) {
        AgentExecutionContext agentContext = input.context();
        return ToolExecutorContext.builder()
                .toolManager(getToolManager())
                .toolCallTracker(agentState.getToolCallTracker())
                .toolContext(ToolContext.builder()
                        .abortSignal(agentContext.getAbortSignal())
                        .build())
                .build();
    }
}
